### PR TITLE
T197836 Use UTC for everything 

### PR DESCRIPTION
**Pull request by davidbarratt**

### CODE REVIEW

**Review by aezell — APPROVED** [review]
Looks good to me. I searched `master` for uses of `local()` and they seem to all be changed with this PR.

**Comment by dayllanmaza** [comment]
What about client/src/components/takedown/create/dmca/dmca.js:151. Why is that using LA timezone?

**Comment by davidbarratt** [comment]
@dayllanmaza I think the template (that is posted on wiki) posts it in San Fransisco time (and looking at the `format()` it looks like it includes the timezone). But perhaps that should be changed as well? Should I ask?

**Comment by dayllanmaza** [comment]
Sure, it doens't hurt to ask. Other than this, it looks good :+1:

**Comment by davidbarratt** [comment]
This should be ready for re-review! :)

**Review by dayllanmaza — APPROVED** [review]

**Pull request merged**
